### ISSUE TITLE
Add me as contributor please !

### ISSUE THREAD

**Issue by heticeric** [golfw/ES6-priou#18]
Hep @golfw, I'd like to pull request too.

**Comment by golfw** [comment]
I think that you're already a contributor 

<img width="770" alt="capture d ecran 2017-10-24 a 00 21 11" src="https://user-images.githubusercontent.com/17832504/31916062-4b7505f6-b851-11e7-843d-fd1ca6686d0e.png">

**Comment by heticeric** [comment]
OK let's see. Thanks for your reactivity !
